### ISSUE TITLE
[Config] Custom keywords

### ISSUE THREAD

**Issue by pwnxpl0it** [pwnxpl0it/idkmng#1]
Custom keywords that will be replaced automatically.
will be added  in the config directory,
like the following structure:

```toml
AUTHOR="Mohamed Tarek"
ANOTHER="test "
```
given a template like: 
```toml
#--snip--
content='''
 Coded by {{$AUTHOR}}
 {{$ANOTHER}}
'''
```
will generate a file with the following content:
```
Coded by Mohamed Tarek
test
```
