### ISSUE TITLE
Functions are not working when used inside path

### ISSUE THREAD

**Issue by pwnxpl0it** [pwnxpl0it/idkmng#23]
Calling functions like read doesn't work when called inside path

example: 
```toml
[[files]]
path="{{$name:read}}"
content=""
```
