### ISSUE TITLE
Template Options

### ISSUE THREAD

**Issue by pwnxpl0it** [pwnxpl0it/idkmng#46]
define custom options inside the template,such as using git, and other features that will be added.

```toml
[options]
git=false
project_root="{{$PROJECTNAME}}"
```
